project_id = "paprssfxjfpahjbylxbl"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54328
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_sms_confirmations = false

[edge-runtime]
enabled = true
port = 54329

[functions.generate-search-strategies]
verify_jwt = false

[functions.search-online-stores]
verify_jwt = false

[functions.search-google-shopping]
verify_jwt = false

[functions.search-stores]
verify_jwt = false

[functions.unified-deduplication]
verify_jwt = false

[functions.verify-store-maps]
verify_jwt = false