// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://paprssfxjfpahjbylxbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhcHJzc2Z4amZwYWhqYnlseGJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0ODY3NjEsImV4cCI6MjA2ODA2Mjc2MX0.CVD0UCPtmHlny7u5onZtzUcDwQLL-d55TCxfOUuj3dU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});