// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuaalafehhwhnyarpxhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1YWFsYWZlaGh3aG55YXJweGh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1ODczMDQsImV4cCI6MjA2ODE2MzMwNH0._bv8iwlc2hQGxSjIs5vTvUbf425cW2Ydq61gYsQqVaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});